version: '3.4'

services:
  next:
    image: next
    container_name: next
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
