image: ubuntu:latest
stages:
  - deploy
  - deploy-production
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  environment:
    name: development
  script:
    - echo $SSH_HOST_IP;ssh ubuntu@3.0.102.186 "cd next;git checkout dev;git reset --hard origin/dev;git pull;docker-compose up --build -d"
  only:
    - dev

deploy-production:
  stage: deploy
  environment:
    name: production
  script:
    - echo $SSH_HOST_IP;ssh ubuntu@3.0.102.186 "cd next;git checkout dev;git reset --hard origin/dev;git pull;docker-compose up --build -d"
  only:
    - main
  when: manual
